### ISSUE TITLE
Need clearification for production

### ISSUE THREAD

**Issue by IamDixit** [DrewIndeed/repack-tester-app#1]
> ChunkManager.configure({
>   storage: AsyncStorage,
>   resolveRemoteChunk: async (chunkId) => {
>     return {
>       url: `http://localhost:5000/${chunkId}`,
>     };
>   },
> });

I am assuming your local server for the app is running on port 5000 hence you mentioned the same on the above line, what will be the configuration for the production build?

**Comment by DrewIndeed** [comment]
Oh hey @IamDixit, 

Check out this repo: https://github.com/DrewIndeed/RN-repack-lazy-loading, just care about the commits from the one saying **"Merge pull request #1 from DrewIndeed/before-async"** and backwards, the rest forward is not related to Repack.

It is better implemented using Repack, this repo is just the sample I separated from Repack examples. 

So to answer your question, it actually depends on your use case. From the suggested repo, I only want to use **async chunks** as local chunks, so in my index.js, I get rid of that ChunkManager config completely. Then, I create the build version of Repack with commands as usual.

**BUT, THE IMPORTANT THINGS I MADE IT WORK ARE: **
+ Lazy load your Components / Pages with _** Webpack magic comments**_ , otherwise, their names will be a mess when webpack builds them -> error: cannot get resources / load chunks OR cannot fin from "http://blabla"\

+ babel.config.js should have comment as true:
`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  comments: true,
};`

+ webpack.config.js, at this part: 
`new ReactNative.OutputPlugin({
      platform,
      devServerEnabled: devServer.enabled,
      localChunks: [/Async/],
      localChunks: [
        // fill in the async chunks names here = they are the names you use in the magic comments
        // I suggest using explicit string names, not regex
      ],
      remoteChunksOutput: path.join(__dirname, 'build', platform, 'remote'),
    }),

+ Scripts in package,json:
`
"scripts": {
    "prepare": "exit 0",
    "test": "exit 0",
    "lint": "exit 0",
    "tsc": "exit 0",
    "build": "exit 0",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native webpack-start",
    "bundle": "react-native webpack-bundle --platform ios --entry-file index.js --bundle-output ./dist/index.bundle --dev=false",
    "webpack": "PLATFORM=ios webpack -c webpack.config.js"
  }
`
